- Gemfile
> dvicefuruta

- README.md
#What
READMEにてDB設計記述
#Why
DB設計可視化のため。
[https://app.lucidchart.com/invitations/accept/cfd3dff9-2516-48df-a4e0-79c4012a4e12](https://app.lucidchart.com/invitations/accept/cfd3dff9-2516-48df-a4e0-79c4012a4e12)
> [WIP]Revert "README DB設計"

- README.md
#What
READMEにてDB設計記述
#Why
DB設計可視化のため。
[https://app.lucidchart.com/invitations/accept/cfd3dff9-2516-48df-a4e0-79c4012a4e12](https://app.lucidchart.com/invitations/accept/cfd3dff9-2516-48df-a4e0-79c4012a4e12)
> [WIP]README DB設計記述

- Gemfile
- Gemfile.lock
- app/assets/javascripts/users.coffee
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/users.scss
- app/controllers/items_controller.rb
- app/controllers/users_controller.rb
- app/helpers/users_helper.rb
- test/controllers/users_controller_test.rb
scssファイル作成
fontawesome導入
pry rails 導入
controller
チーム開発するため
> Scss fontawesome

- db/schema.rb
> db:create migrate

- db/schema.rb
> db created

- config/routes.rb
> profiles root

- README.md
- db/migrate/20200523061458_remove_birth_year_in_profiles.rb
- db/schema.rb
birth_year、birth_month、birth_dayカラム削除
birthdayカラム追加
(readme修正済み）
birthday情報の登録や、表示を簡単にするため。
> edit-finish

- app/assets/stylesheets/_sale.scss
- app/views/items/new.html.haml
#What
商品出品ページのフロントを実装しました。
#Why
フリマアプリの根幹機能のページのため。
[https://gyazo.com/b36c64ad08aea90edc7dd6e4bfe94061](https://gyazo.com/b36c64ad08aea90edc7dd6e4bfe94061)
[https://gyazo.com/95de9fa30458cc91e17ecd839ce97e5e](https://gyazo.com/95de9fa30458cc91e17ecd839ce97e5e)
[https://gyazo.com/3c2d411368482dca24e1ad3c20f52db9](https://gyazo.com/3c2d411368482dca24e1ad3c20f52db9)
[https://gyazo.com/b8c11d2edc6452079f4642e5a5a7ef3c](https://gyazo.com/b8c11d2edc6452079f4642e5a5a7ef3c)
> [WIP]商品出品ページマークアップ実装

- app/assets/stylesheets/_login.scss
- app/views/devise/sessions/new.html.haml
ログイン時のビューを作成しました
サービスを利用するために必要なため
> login_view_finish

- db/migrate/20200525105618_add_column_to_users.rb
- db/schema.rb
usersテーブルにnicknameカラム追加しました。
必要な機能のため
> ユーザー名のカラム追加

- app/assets/stylesheets/_signin.scss
- app/controllers/application_controller.rb
- app/controllers/home_controller.rb
- app/controllers/users/confirmations_controller.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- app/controllers/users/passwords_controller.rb
- app/controllers/users/registrations_controller.rb
- app/controllers/users/sessions_controller.rb
- app/controllers/users/unlocks_controller.rb
- app/models/address.rb
- app/models/user.rb
- app/views/devise/registrations/create_profile.html.haml
- app/views/devise/registrations/new.html.haml
- app/views/devise/registrations/new_address.html.haml
- app/views/devise/registrations/new_profile.html.haml
- app/views/devise/sessions/new.html.haml
- app/views/home/index.html.haml
- app/views/home/new.html.haml
- config/initializers/devise.rb
- config/routes.rb
- db/migrate/20200526104216_change_data_phone_number_to_profiles.rb
- db/migrate/20200526115358_change_data_birthday_to_profiles.rb
- db/schema.rb
新規登録機能実装（ウィザード形式）
ログイン、ログアウト機能実装
必要な機能のため
> Signup page

- app/views/devise/sessions/new.html.haml
- app/views/items/index.html.haml
トップページのヘッダーに新規登録、ログインページへのリンクを追加しました。
ログイン時は、マイページとログアウトへのリンクになっています。
必要な機能のため
> トップページのヘッダーに新規登録、ログインのリンク追加

- db/migrate/20200528140712_rename_src_culumn_to_images.rb
- db/schema.rb
不要なマイグレーションファイルを削除しました。
重複するファイルがあったため
> 不要なマイグレーションファイル削除

- Gemfile
- Gemfile.lock
- app/models/profile.rb
- app/models/user.rb
テストに使用するgemをインストール
バリデーション追加
必要な機能のため
> テストのgemインストール

- spec/factories/addresses.rb
- spec/factories/cards.rb
- spec/factories/profiles.rb
- spec/factories/users.rb
- spec/models/address_spec.rb
- spec/models/card_spec.rb
- spec/models/profile_spec.rb
- spec/models/user_spec.rb
- spec/rails_helper.rb
user、address、profile、cardのテストコード記入
動作確認のため
> user、address、profile、cardのテストコード記入

- spec/factories/item.rb
- spec/models/item_spec.rb
#What
商品出品機能の単体テストを実施しました。
#Why
仕様漏れがないようにするため。
> 商品出品機能のテスト

- Gemfile.lock
- app/assets/javascripts/slide_image.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/slide.scss
- app/controllers/items_controller.rb
- app/models/category.rb
- app/views/items/show.html.haml
- app/views/layouts/application.html.haml
#What
商品の詳細ページの表示を実装しました。
#Why
フリマアプリにおける必要なページのため。
> [WIP]商品詳細表示機能の実装

- app/assets/javascripts/new_item.js
- app/assets/stylesheets/_detail.scss
- app/assets/stylesheets/_sale.scss
- app/controllers/purchases_controller.rb
- app/models/item.rb
- app/views/home/edit.html.haml
- app/views/items/_form.html.haml
- app/views/items/edit.html.haml
- app/views/items/show.html.haml
＃What
・「フリペイ」への表記の変更
・各のページのビューの修正
・商品出品、編集時　販売利益の反映
・購入機能の不具合修正
#Why
根幹機能関わる部分のため。
> いくつかの箇所の修正

- app/assets/stylesheets/_signin.scss
- app/models/address.rb
- app/models/profile.rb
> バリデーション修正、エラー時のビュー修正

- app/assets/javascripts/category_box.js
- app/models/address.rb
- db/migrate/20200604023138_change_data_postal_code_to_addresses.rb
- db/schema.rb
ユーザー情報のバリデーション修正
出品時のカテゴリボックス修正
必要な機能のため
> バリデーション修正、出品時のカテゴリ機能訂正

- Gemfile.lock
- app/assets/javascripts/category_box.js
- app/assets/javascripts/category_edit.js
- app/assets/stylesheets/_sale.scss
- app/views/items/edit.html.haml
> 商品編集（カテゴリ機能実装）

- app/assets/javascripts/new_item.js
＃What
編集ページの画像の選択のボックスの表示の修正
#Why
ビューを整えるため。
> 編集ページの画像表示機能修正

- app/controllers/items_controller.rb
- app/views/items/_form.html.haml
- app/views/users/show.html.haml
- config/application.rb
#What
・不要なコードの削除
・マイページのヘッダーを編集
#Why
コードを綺麗にするため。
機能性を向上するため。
> いくつか気になるところの修正

- README.md
- app/assets/javascripts/comment.js
- app/assets/javascripts/comments.coffee
- app/assets/stylesheets/_comment.scss
- app/assets/stylesheets/_detail.scss
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/comments.scss
- app/controllers/comments_controller.rb
- app/controllers/items_controller.rb
- app/helpers/comments_helper.rb
- app/models/comment.rb
- app/models/item.rb
- app/models/user.rb
- app/views/comments/create.json.jbuilder
- app/views/comments/restore.json.jbuilder
- app/views/items/comment/_comment_delete_restore_btn.html.haml
- app/views/items/comment/_comment_name.html.haml
- app/views/items/show.html.haml
- config/routes.rb
- db/migrate/20200606052916_create_comments.rb
- db/schema.rb
- spec/factories/comments.rb
- spec/helpers/comments_helper_spec.rb
- spec/models/comment_spec.rb
- spec/requests/comments_request_spec.rb
＃What
商品に対するコメント機能の実装
　・コメント
　　出品者のみコメント削除、復元、完全に削除が可能
　・コメント仮削除時は「コメントは削除されました」の表示
　・完全に削除後は消す。
　・出品者とその他ユーザーの色分け
　・ajax（非同期通信）
#Why
フリマアプリにおける必要な機能のため。
> [WIP]商品へのコメント機能の実装

- app/assets/stylesheets/_detail.scss
- app/assets/stylesheets/_mypage.scss
- app/assets/stylesheets/favorites.scss
- app/controllers/favorites_controller.rb
- app/controllers/items_controller.rb
- app/controllers/users_controller.rb
- app/helpers/favorites_helper.rb
- app/models/favorite.rb
- app/models/item.rb
- app/models/user.rb
- app/views/favorites/_favorite.html.haml
- app/views/favorites/favorite.js.haml
- app/views/favorites/unfavorite.js.haml
- app/views/items/show.html.haml
- app/views/users/favorites.html.haml
- app/views/users/show.html.haml
- config/routes.rb
- db/migrate/20200607021735_create_favorites.rb
- db/migrate/20200607033447_add_favorites_count_to_items.rb
- db/schema.rb
- spec/factories/favorites.rb
- spec/helpers/favorites_helper_spec.rb
- spec/models/favorite_spec.rb
- spec/requests/favorites_request_spec.rb
#What
商品のお気に入り機能
・商品詳細ページにてお気に入りボタン設置
・お気に入りした場合　ビューの変更（☆→★）
・お気に入りカウント設置
・ajax（非同期通信）も実装
・ユーザーマイページにて一覧表示
#Why
フリマアプリにて必要な機能のため。
> [WIP]お気に入り機能の実装
